# site settings
# comment
title: Kyle Dawson, PhD
subtitle: Welcome to my Website
email: drkylewdawson@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://kyledawson.github.io # the base hostname & protocol for your site
author:
street_address: 1205 Sheldon Cove, Ste 1A
city: Austin
state: TX
zip_code: 78753
country: United States of America
phone: +1 (512) 649-8332

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kyledawson
  LinkedIn: https://www.linkedin.com/in/kylewdawson
  x-twitter: https://x.com/drkyledawson

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

destination: ./build
