# site settings
# comment
title: Kyle Dawson, PhD
subtitle: Welcome to my Website
email: drkylewdawson@gmail.com
description: I am a Sr. Data Scientist with subject matter expertise <br />in Atmospheric Science and Sustainable Greenhouse Gas Emissions Monitoring
baseurl: ""  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kyle W. Dawson
street_address: 1205 Sheldon Cove, Ste 1A
city: Austin
state: TX
zip_code: 78753
country: United States of America
phone: +1 (512) 649-8332

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kyledawson
  LinkedIn: https://www.linkedin.com/in/kylewdawson
  Twitter: https://x.com/drkyledawson
  Map: https://maps.app.goo.gl/LxqioWJMbstr8nxW9

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

destination: ./build
